services:
    db:
        image: postgres:18
        container_name: household_budget_db
        environment:
            POSTGRES_USER: app_user
            POSTGRES_PASSWORD: app_password
            POSTGRES_DB: household_budget
        ports:
            - '5432:5432'
        volumes:
            - household_budget_pgdata:/var/lib/postgresql

    mailpit:
        image: axllent/mailpit:latest
        container_name: household_budget_mailpit
        ports:
            - '1025:1025'
            - '8025:8025'

volumes:
    household_budget_pgdata:
